import { renderBlockToLiquid, renderEmailToLiquid } from '@/utils/liquidRenderer';
import { Block, BlockTemplate } from '@/types';

// Mock templates for testing
const mockTemplates: BlockTemplate[] = [
  {
    type: 'text',
    name: 'Text',
    template: '<div style="color: {{ color | default: \'#333\' }};">{{ content | default: \'Default text\' }}</div>',
    defaultProps: { content: 'Test text', color: '#333' }
  }
];

describe('liquidRenderer', () => {
  test('renderBlockToLiquid should render text block correctly', () => {
    const block: Block = {
      id: 'test-1',
      type: 'text',
      props: { content: 'Hello World', color: '#ff0000' }
    };

    const result = renderBlockToLiquid(block, mockTemplates);
    expect(result).toContain('Hello World');
    expect(result).toContain('#ff0000');
  });

  test('renderEmailToLiquid should handle multiple blocks', () => {
    const blocks: Block[] = [
      {
        id: 'test-1',
        type: 'text',
        props: { content: 'First block', color: '#333' }
      },
      {
        id: 'test-2',
        type: 'text',
        props: { content: 'Second block', color: '#666' }
      }
    ];

    // Mock the loadBlockTemplates function
    jest.mock('@/utils/liquidRenderer', () => ({
      ...jest.requireActual('@/utils/liquidRenderer'),
      loadBlockTemplates: () => mockTemplates
    }));

    const result = renderEmailToLiquid(blocks);
    expect(result).toContain('Generated by Braze Email Builder');
    expect(result).toContain('First block');
    expect(result).toContain('Second block');
  });
});